In [2]:
from gamedata import hard_sales as hs
from typing import Optional, List
import pandas as pd
from datetime import datetime, timedelta

In [ ]:
hard_sales_df = hs.load_hard_sales()
hs.get_hw_names(hard_sales_df)


hard_sales_df = hard_sales_df[hard_sales_df['hw'].isin(['NSW', 'NS2', 'PS5', 'PS4', "XSX"])]
# hard_sales_dfの最後から20行程度を表示する
hard_sales_df.tail(20)

,weekly_id,begin_date,end_date,report_date,period_date,hw,units,year,month,mday,week,delta_day,delta_week,delta_month,delta_year,avg_units,sum_units,launch_date,maker_name,full_name
8193,2025-07-06_NS2,2025-06-30,2025-07-06,2025-07-06,7,NS2,128643,2025,7,6,27,31,4,1,0,18377,1530826,2025-06-05,Nintendo,Nintendo Switch2
8194,2025-07-06_NSW,2025-06-30,2025-07-06,2025-07-06,7,NSW,17712,2025,7,6,27,3047,435,100,8,2530,35811161,2017-03-03,Nintendo,Nintendo Switch
8195,2025-07-06_PS4,2025-06-30,2025-07-06,2025-07-06,7,PS4,21,2025,7,6,27,4152,593,137,11,3,9490618,2014-02-22,SONY,PlayStation4
8196,2025-07-06_PS5,2025-06-30,2025-07-06,2025-07-06,7,PS5,8629,2025,7,6,27,1697,242,56,5,1232,6918908,2020-11-12,SONY,PlayStation5
8197,2025-07-06_XSX,2025-06-30,2025-07-06,2025-07-06,7,XSX,529,2025,7,6,27,1699,242,56,5,75,681127,2020-11-10,Microsoft,Xbox Series X|S
8198,2025-07-13_NS2,2025-07-07,2025-07-13,2025-07-13,7,NS2,71885,2025,7,13,28,38,5,1,0,10269,1602711,2025-06-05,Nintendo,Nintendo Switch2
8199,2025-07-13_NSW,2025-07-07,2025-07-13,2025-07-13,7,NSW,13411,2025,7,13,28,3054,436,100,8,1915,35824572,2017-03-03,Nintendo,Nintendo Switch
8200,2025-07-13_PS4,2025-07-07,2025-07-13,2025-07-13,7,PS4,30,2025,7,13,28,4159,594,137,11,4,9490648,2014-02-22,SONY,PlayStation4
8201,2025-07-13_PS5,2025-07-07,2025-07-13,2025-07-13,7,PS5,7262,2025,7,13,28,1704,243,56,5,1037,6926170,2020-11-12,SONY,PlayStation5
8202,2025-07-13_XSX,2025-07-07,2025-07-13,2025-07-13,7,XSX,247,2025,7,13,28,1706,243,56,5,35,681374,2020-11-10,Microsoft,Xbox Series X|S
8203,2025-07-20_NS2,2025-07-14,2025-07-20,2025-07-20,7,NS2,152165,2025,7,20,29,45,6,1,0,21737,1754876,2025-06-05,Nintendo,Nintendo Switch2
8204,2025-07-20_NSW,2025-07-14,2025-07-20,2025-07-20,7,NSW,11766,2025,7,20,29,3061,437,100,8,1680,35836338,2017-03-03,Nintendo,Nintendo Switch
8205,2025-07-20_PS4,2025-07-14,2025-07-20,2025-07-20,7,PS4,22,2025,7,20,29,4166,595,137,11,3,9490670,2014-02-22,SONY,PlayStation4
8206,2025-07-20_PS5,2025-07-14,2025-07-20,2025-07-20,7,PS5,6148,2025,7,20,29,1711,244,56,5,878,6932318,2020-11-12,SONY,PlayStation5
8207,2025-07-20_XSX,2025-07-14,2025-07-20,2025-07-20,7,XSX,150,2025,7,20,29,1713,244,56,5,21,681524,2020-11-10,Microsoft,Xbox Series X|S
8208,2025-07-27_NS2,2025-07-21,2025-07-27,2025-07-27,7,NS2,92013,2025,7,27,30,52,7,1,0,13144,1846889,2025-06-05,Nintendo,Nintendo Switch2
8209,2025-07-27_NSW,2025-07-21,2025-07-27,2025-07-27,7,NSW,14643,2025,7,27,30,3068,438,100,8,2091,35850981,2017-03-03,Nintendo,Nintendo Switch
8210,2025-07-27_PS4,2025-07-21,2025-07-27,2025-07-27,7,PS4,18,2025,7,27,30,4173,596,137,11,2,9490688,2014-02-22,SONY,PlayStation4
8211,2025-07-27_PS5,2025-07-21,2025-07-27,2025-07-27,7,PS5,6920,2025,7,27,30,1718,245,56,5,988,6939238,2020-11-12,SONY,PlayStation5
8212,2025-07-27_XSX,2025-07-21,2025-07-27,2025-07-27,7,XSX,271,2025,7,27,30,1720,245,56,5,38,681795,2020-11-10,Microsoft,Xbox Series X|S

In [3]:
latest_df = hs.extract_latest(hard_sales_df)
latest_df

,weekly_id,begin_date,end_date,report_date,period_date,hw,units,year,month,mday,week,delta_day,delta_week,delta_year,avg_units,sum_units,launch_date,maker_name,full_name
8203,2025-07-20_NSW,2025-07-14,2025-07-20,2025-07-20,7,NSW,11766,2025,7,20,29,3061,437,8,1680,35836338,2017-03-03,Nintendo,Nintendo Switch
8204,2025-07-20_NS2,2025-07-14,2025-07-20,2025-07-20,7,NS2,152165,2025,7,20,29,45,6,0,21737,1754876,2025-06-05,Nintendo,Nintendo Switch2
8205,2025-07-20_PS4,2025-07-14,2025-07-20,2025-07-20,7,PS4,22,2025,7,20,29,4166,595,11,3,9490670,2014-02-22,SONY,PlayStation4
8206,2025-07-20_PS5,2025-07-14,2025-07-20,2025-07-20,7,PS5,6148,2025,7,20,29,1711,244,5,878,6932318,2020-11-12,SONY,PlayStation5
8207,2025-07-20_XSX,2025-07-14,2025-07-20,2025-07-20,7,XSX,150,2025,7,20,29,1713,244,5,21,681524,2020-11-10,Microsoft,Xbox Series X|S

In [22]:
filtered_df = hs.extract_by_date(hard_sales_df, '2025-06-05')
filtered_df

,weekly_id,begin_date,end_date,report_date,period_date,hw,units,year,month,mday,week,delta_day,delta_week,delta_month,delta_year,avg_units,sum_units,launch_date,maker_name,full_name
8173,2025-06-08_NS2,2025-06-02,2025-06-08,2025-06-08,7,NS2,947931,2025,6,8,23,3,0,0,0,135418,947931,2025-06-05,Nintendo,Nintendo Switch2
8174,2025-06-08_NSW,2025-06-02,2025-06-08,2025-06-08,7,NSW,16611,2025,6,8,23,3019,431,99,8,2373,35752038,2017-03-03,Nintendo,Nintendo Switch
8175,2025-06-08_PS4,2025-06-02,2025-06-08,2025-06-08,7,PS4,24,2025,6,8,23,4124,589,136,11,3,9490524,2014-02-22,SONY,PlayStation4
8176,2025-06-08_PS5,2025-06-02,2025-06-08,2025-06-08,7,PS5,20782,2025,6,8,23,1669,238,55,5,2968,6882811,2020-11-12,SONY,PlayStation5
8177,2025-06-08_XSX,2025-06-02,2025-06-08,2025-06-08,7,XSX,333,2025,6,8,23,1671,238,55,5,47,679793,2020-11-10,Microsoft,Xbox Series X|S

In [5]:
df1M = hs.extract_week_reached_units(hard_sales_df, 1500000)
df1M

,weekly_id,begin_date,end_date,report_date,period_date,hw,units,year,month,mday,week,delta_day,delta_week,delta_year,avg_units,sum_units,launch_date,maker_name,full_name
8194,2025-07-06_NS2,2025-06-30,2025-07-06,2025-07-06,7,NS2,128643,2025,7,6,27,31,4,0,18377,1530826,2025-06-05,Nintendo,Nintendo Switch2
6285,2017-08-27_NSW,2017-08-21,2017-08-27,2017-08-27,7,NSW,85503,2017,8,27,34,177,25,0,12214,1565273,2017-03-03,Nintendo,Nintendo Switch
5701,2015-08-02_PS4,2015-07-27,2015-08-02,2015-08-02,7,PS4,13192,2015,8,2,31,526,75,1,1884,1508068,2014-02-22,SONY,PlayStation4
7444,2022-04-03_PS5,2022-03-28,2022-04-03,2022-04-03,7,PS5,30666,2022,4,3,13,507,72,2,4380,1528183,2020-11-12,SONY,PlayStation5

In [ ]:
# 昨年のデータ
last_year_df = hard_sales_df[hard_sales_df["year"] == 2024]
last_year_df

,weekly_id,begin_date,end_date,report_date,period_date,hw,units,year,month,mday,week,delta_day,delta_week,delta_month,delta_year,avg_units,sum_units,launch_date,maker_name,full_name
7877,2024-01-07_NSW,2024-01-01,2024-01-07,2024-01-07,7,NSW,104551,2024,1,7,1,2501,357,82,7,14935,31891225,2017-03-03,Nintendo,Nintendo Switch
7878,2024-01-07_PS4,2024-01-01,2024-01-07,2024-01-07,7,PS4,737,2024,1,7,1,3606,515,119,10,105,9476969,2014-02-22,SONY,PlayStation4
7879,2024-01-07_PS5,2024-01-01,2024-01-07,2024-01-07,7,PS5,41126,2024,1,7,1,1151,164,38,4,5875,5005983,2020-11-12,SONY,PlayStation5
7880,2024-01-07_XSX,2024-01-01,2024-01-07,2024-01-07,7,XSX,1324,2024,1,7,1,1153,164,38,4,189,541431,2020-11-10,Microsoft,Xbox Series X|S
7882,2024-01-14_NSW,2024-01-08,2024-01-14,2024-01-14,7,NSW,46604,2024,1,14,2,2508,358,82,7,6657,31937829,2017-03-03,Nintendo,Nintendo Switch
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8084,2024-12-22_XSX,2024-12-16,2024-12-22,2024-12-22,7,XSX,3389,2024,12,22,51,1503,214,49,4,484,657167,2020-11-10,Microsoft,Xbox Series X|S
8085,2024-12-29_NSW,2024-12-23,2024-12-29,2024-12-29,7,NSW,76548,2024,12,29,52,2858,408,93,7,10935,34895777,2017-03-03,Nintendo,Nintendo Switch
8086,2024-12-29_PS4,2024-12-23,2024-12-29,2024-12-29,7,PS4,37,2024,12,29,52,3963,566,130,10,5,9489960,2014-02-22,SONY,PlayStation4
8087,2024-12-29_PS5,2024-12-23,2024-12-29,2024-12-29,7,PS5,27130,2024,12,29,52,1508,215,49,4,3875,6419006,2020-11-12,SONY,PlayStation5
8088,2024-12-29_XSX,2024-12-23,2024-12-29,2024-12-29,7,XSX,1161,2024,12,29,52,1510,215,49,4,165,658328,2020-11-10,Microsoft,Xbox Series X|S

In [23]:
nintendo_df = hard_sales_df[hard_sales_df["maker_name"].isin(['Nintendo'])]
nintendo_df.tail(20)

,weekly_id,begin_date,end_date,report_date,period_date,hw,units,year,month,mday,week,delta_day,delta_week,delta_month,delta_year,avg_units,sum_units,launch_date,maker_name,full_name
8157,2025-05-11_NSW,2025-05-05,2025-05-11,2025-05-11,7,NSW,29710,2025,5,11,19,2991,427,98,8,4244,35666585,2017-03-03,Nintendo,Nintendo Switch
8161,2025-05-18_NSW,2025-05-12,2025-05-18,2025-05-18,7,NSW,24478,2025,5,18,20,2998,428,98,8,3496,35691063,2017-03-03,Nintendo,Nintendo Switch
8165,2025-05-25_NSW,2025-05-19,2025-05-25,2025-05-25,7,NSW,24289,2025,5,25,21,3005,429,98,8,3469,35715352,2017-03-03,Nintendo,Nintendo Switch
8169,2025-06-01_NSW,2025-05-26,2025-06-01,2025-06-01,7,NSW,20075,2025,6,1,22,3012,430,99,8,2867,35735427,2017-03-03,Nintendo,Nintendo Switch
8173,2025-06-08_NS2,2025-06-02,2025-06-08,2025-06-08,7,NS2,947931,2025,6,8,23,3,0,0,0,135418,947931,2025-06-05,Nintendo,Nintendo Switch2
8174,2025-06-08_NSW,2025-06-02,2025-06-08,2025-06-08,7,NSW,16611,2025,6,8,23,3019,431,99,8,2373,35752038,2017-03-03,Nintendo,Nintendo Switch
8178,2025-06-15_NS2,2025-06-09,2025-06-15,2025-06-15,7,NS2,153205,2025,6,15,24,10,1,0,0,21886,1101136,2025-06-05,Nintendo,Nintendo Switch2
8179,2025-06-15_NSW,2025-06-09,2025-06-15,2025-06-15,7,NSW,13319,2025,6,15,24,3026,432,99,8,1902,35765357,2017-03-03,Nintendo,Nintendo Switch
8183,2025-06-22_NS2,2025-06-16,2025-06-22,2025-06-22,7,NS2,140026,2025,6,22,25,17,2,0,0,20003,1241162,2025-06-05,Nintendo,Nintendo Switch2
8184,2025-06-22_NSW,2025-06-16,2025-06-22,2025-06-22,7,NSW,12769,2025,6,22,25,3033,433,99,8,1824,35778126,2017-03-03,Nintendo,Nintendo Switch
8188,2025-06-29_NS2,2025-06-23,2025-06-29,2025-06-29,7,NS2,161021,2025,6,29,26,24,3,0,0,23003,1402183,2025-06-05,Nintendo,Nintendo Switch2
8189,2025-06-29_NSW,2025-06-23,2025-06-29,2025-06-29,7,NSW,15323,2025,6,29,26,3040,434,99,8,2189,35793449,2017-03-03,Nintendo,Nintendo Switch
8193,2025-07-06_NS2,2025-06-30,2025-07-06,2025-07-06,7,NS2,128643,2025,7,6,27,31,4,1,0,18377,1530826,2025-06-05,Nintendo,Nintendo Switch2
8194,2025-07-06_NSW,2025-06-30,2025-07-06,2025-07-06,7,NSW,17712,2025,7,6,27,3047,435,100,8,2530,35811161,2017-03-03,Nintendo,Nintendo Switch
8198,2025-07-13_NS2,2025-07-07,2025-07-13,2025-07-13,7,NS2,71885,2025,7,13,28,38,5,1,0,10269,1602711,2025-06-05,Nintendo,Nintendo Switch2
8199,2025-07-13_NSW,2025-07-07,2025-07-13,2025-07-13,7,NSW,13411,2025,7,13,28,3054,436,100,8,1915,35824572,2017-03-03,Nintendo,Nintendo Switch
8203,2025-07-20_NS2,2025-07-14,2025-07-20,2025-07-20,7,NS2,152165,2025,7,20,29,45,6,1,0,21737,1754876,2025-06-05,Nintendo,Nintendo Switch2
8204,2025-07-20_NSW,2025-07-14,2025-07-20,2025-07-20,7,NSW,11766,2025,7,20,29,3061,437,100,8,1680,35836338,2017-03-03,Nintendo,Nintendo Switch
8208,2025-07-27_NS2,2025-07-21,2025-07-27,2025-07-27,7,NS2,92013,2025,7,27,30,52,7,1,0,13144,1846889,2025-06-05,Nintendo,Nintendo Switch2
8209,2025-07-27_NSW,2025-07-21,2025-07-27,2025-07-27,7,NSW,14643,2025,7,27,30,3068,438,100,8,2091,35850981,2017-03-03,Nintendo,Nintendo Switch

In [9]:
# switch_dfを月毎に集計する
switch_monthly_sales = hs.aggregate_monthly_sales(switch_df)
# 月毎のNintendo Switch*の販売台数を表示する
switch_monthly_sales.tail(20)

     year  month   hw  monthly_units  sum_units
83   2024      2  NSW         190786   32218742
84   2024      3  NSW         289673   32508415
85   2024      4  NSW         207496   32715911
86   2024      5  NSW         235840   32951751
87   2024      6  NSW         225316   33177067
88   2024      7  NSW         229316   33406383
89   2024      8  NSW         227913   33634296
90   2024      9  NSW         308404   33942700
91   2024     10  NSW         245466   34188166
92   2024     11  NSW         255401   34443567
93   2024     12  NSW         452210   34895777
94   2025      1  NSW         260447   35156224
95   2025      2  NSW         167188   35323412
96   2025      3  NSW         171921   35495333
97   2025      4  NSW          85484   35580817
98   2025      5  NSW         134535   35715352
99   2025      6  NS2        1402183    1402183
100  2025      6  NSW          78097   35793449
101  2025      7  NS2         352693    1754876
102  2025      7  NSW          42889   35836338